<title>Pengertian Framework 1461900124</title>
<h1>Pengertian Framework</h1>
<p><a href="{{url('/home_1461900124')}}">Back To Home</a></p>
<p>framework merupakan kerangka kerja yang memudahkan developer untuk membangun sebuah aplikasi / web tanpa perlu membangunnya mulai dari 0. Karena didalam framework sudah tersedia berbagai macam komponen dan cukup memanggilnya saja dengan class / function.</p>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
    <p>Adapun beberapa jenis framework yaitu</p>
    <ol style="margin-bottom:0cm;list-style-type: decimal;">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><strong>Laravel</strong><br>&nbsp;Kelebihan:<br>&nbsp;-Didokumentasikan secara lengkap<br>&nbsp;-Memiliki banyak tutorial di internet<br>&nbsp;-Kode bisa terstruktur dan sistematis<br>&nbsp;-Banyak digunakan oleh berbagai developer<br>&nbsp;-Menggunakan Model View Controller</li>
    </ol>
</div>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Kekurangan:<br>&nbsp;-Masih banyak metode yang rumit<br>&nbsp;-tidak semua file inti menggunakan garis miring namespace (\)<br>&nbsp;-Perkembangannya tidak pesat seperti ruby<br>&nbsp;-Sulit bagi sistem lama untuk dipindah ke Laravel<br>&nbsp;-Memerlukan bantuan pihak ketiga untuk beberapa masalah</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><strong>CodeIgniter</strong><br>&nbsp;Kelebihan:<br>&nbsp;-Fleksibel untuk dikembangkan<br>&nbsp;-Keamanan canggih<br>&nbsp;-Memiliki kapasitas yang berukuran kecil<br>&nbsp;-Konfigurasi yang sangat mudah<br>&nbsp;-Mendukung chaching web/ database</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Kekurangan:<br>&nbsp;-Tidak memiliki namespace yang modern<br>&nbsp;-Tidak memiliki autoloader<br>&nbsp;-Memiliki masalah di session management<br>&nbsp;-Tidak cocok untuk mega proyek<br>&nbsp;-Testing yang rumit</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><strong>Symfony</strong><br>&nbsp;Kelebihan:<br>&nbsp;-Pengembangan yang bisa lebih cepat<br>&nbsp;-Memiliki bundle dan componen<br>&nbsp;-Maintenance dan test yang mudah<br>&nbsp;-Memiliki komunitas yang besar<br>&nbsp;-Berperforma tinggi<br>&nbsp;<br>&nbsp;Kekurangan:<br>&nbsp;-Memiliki masalah dalam performa kerjanya<br>&nbsp;-Lumayan sulit untuk dipelajari dibanding laravel<br>&nbsp;-Tidak mendukung MVC<br>&nbsp;-Masih menggunakan bahasa php murni<br>&nbsp;-Mengakses data repositori tidak mudah</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><strong>Ruby on Rails<br>&nbsp;</strong>Kelebihan:<br>&nbsp;-Sangat cepat untuk membangun web<br>&nbsp;-Mudah untuk memahami dokumentai<br>&nbsp;-Memiliki banyak komunitas<br>&nbsp;-Memiliki perkembangan yang cepat<br>&nbsp;-Menyediakan API yang baik</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Kekurangan:<br>&nbsp;-Memiliki performa yang kurang baik<br>&nbsp;-Dokumentasi kurang lengkap<br>&nbsp;-Kecepatan booth kurang baik<br>&nbsp;-Tidak banyak digunakan oleh developer<br>&nbsp;-Memerlukan biaya yang mahal</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><strong>CakePHP</strong><br>&nbsp;Kelebihan:<br>&nbsp;-Memiliki dokumentasi yang baik<br>&nbsp;-Perkembangan fitur yang uptodate<br>&nbsp;-Mendukung MVC<br>&nbsp;-Cocok untuk web yang kompleks<br>&nbsp;-Konfigurasi mudah dilakukan</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Kekurangan:<br>&nbsp;-Lebih kompleks untuk dipelajari<br>&nbsp;-Memiliki masalah keamanan<br>&nbsp;-Bukan framework yang sederhana</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>-Tidak mendukung URL fancy<br>&nbsp;-Sulit imigrasi ke versi baru</p>